# Generated by Django 4.1.2 on 2023-06-19 11:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название банка",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер банковской карты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банковские реквизиты",
                "verbose_name_plural": "Банковские реквизиты",
            },
        ),
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Наименование интернет-магазина",
                    ),
                ),
                (
                    "shop_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Мессенджер", "Мессенджер"),
                            ("Web-сайт", "Web-сайт"),
                            ("DarkNet", "DarkNet"),
                        ],
                        default=None,
                        max_length=500,
                        null=True,
                        verbose_name="Тип магазина",
                    ),
                ),
                (
                    "shop_address",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=500,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "shop_messanger_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=500,
                        null=True,
                        verbose_name="Наименование мессенджера",
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Банковская карта", "Банковская карта"),
                            ("Электронные платежи", "Электронные платежи"),
                            ("Криптовалюта", "Криптовалюта"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "crime_place",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Кандалакшский района", "Кандалакшский района"),
                            ("Ковдорский район", "Ковдорский район"),
                            ("Кольский район", "Кольский район"),
                            ("Ловозерский район", "Ловозерский район"),
                            ("Печенгский район", "Печенгский район"),
                            ("Терский район", "Терский район"),
                            ("город Мурманск", "город Мурманск"),
                            (
                                "город Апатиты с подведомственной территорией",
                                "город Апатиты с подведомственной территорией",
                            ),
                            (
                                "ород Кировск с подведомственной территорией",
                                "город Кировск с подведомственной территорией",
                            ),
                            (
                                "город Оленегорск с подведомственной территорией",
                                "город Оленегорск с подведомственной территорией",
                            ),
                            (
                                "город Полярные Зори с подведомственной территорией",
                                "город Полярные Зори с подведомственной территорией",
                            ),
                            ("ЗАТО посёлок Видяево", "ЗАТО посёлок Видяево"),
                            ("ЗАТО город Заозёрск", "ЗАТО город Заозёрск"),
                            ("ЗАТО город Островной", "ЗАТО город Островной"),
                            ("ЗАТО город Североморск", "ЗАТО город Североморск"),
                            ("ЗАТО Александровск", "ЗАТО Александровск"),
                            (
                                "город Мончегорск с подведомственной территорией",
                                "город Мончегорск с подведомственной территорией",
                            ),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Место преступления",
                    ),
                ),
                (
                    "arrest_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата задержания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Скупщик",
                "verbose_name_plural": "Скупщики",
            },
        ),
        migrations.CreateModel(
            name="Clad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_clad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Мастер-клад", "Мастер-клад"),
                            ("Закладка", "Закладка"),
                        ],
                        default="Закладка",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name="Координаты клада (долгота)",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                        verbose_name="Координаты клада (Ширина)",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Фотография клада",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название криптовалюты",
                    ),
                ),
                (
                    "address_wallet",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Адрес кошелька",
                    ),
                ),
            ],
            options={
                "verbose_name": "Криптовалюты",
                "verbose_name_plural": "Криптовалюты",
            },
        ),
        migrations.CreateModel(
            name="InternetAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Логин"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Пароль"
                    ),
                ),
                (
                    "app_password",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Пароль приложения",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Имя аккаунта",
                    ),
                ),
                (
                    "account_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="«Аккаунт-адрес»",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Привязанный номер",
                    ),
                ),
                (
                    "operator_nickname",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ник-нейм оператора",
                    ),
                ),
                (
                    "operator_account",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Аккаунт оператора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аккаунт пакупателя",
                "verbose_name_plural": "Аккаунт пакупателя",
            },
        ),
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imei",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="IMEI-номер"
                    ),
                ),
                (
                    "mobile_brand",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Марка"
                    ),
                ),
                (
                    "mobile_model",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Модель"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Пароль"
                    ),
                ),
            ],
            options={
                "verbose_name": "Телефон",
                "verbose_name_plural": "Телефоны",
            },
        ),
        migrations.CreateModel(
            name="MobileNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=17, verbose_name="Номер телефона"),
                ),
            ],
            options={
                "verbose_name": "Номер телефона",
                "verbose_name_plural": "Телефонные номера",
            },
        ),
        migrations.CreateModel(
            name="OnlinePay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название платежной системы",
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер счета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Онлайн-платежи",
                "verbose_name_plural": "Онлайн-платежи",
            },
        ),
        migrations.CreateModel(
            name="StuffType",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип вещества",
                "verbose_name_plural": "Тип вещества",
            },
        ),
        migrations.CreateModel(
            name="Stuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mass",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Масса",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("мг", "мг"), ("г", "г"), ("кг", "кг")],
                        default="мг",
                        max_length=255,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "stuff_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="buyer.stufftype",
                        verbose_name="Вещество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вещество",
                "verbose_name_plural": "Вещества",
            },
        ),
        migrations.CreateModel(
            name="PhotoClad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("describe", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, null=True, upload_to="files/")),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="buyer.buyer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyerStuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buyer.buyer"
                    ),
                ),
                (
                    "mobile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buyer.stuff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyerMobileNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buyer.buyer"
                    ),
                ),
                (
                    "mobile_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buyer.mobilenumber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyerMobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buyer.buyer"
                    ),
                ),
                (
                    "mobile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buyer.mobile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyerClads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buyer.buyer"
                    ),
                ),
                (
                    "clad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buyer.clad"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="buyer",
            name="accounts",
            field=models.ManyToManyField(
                default=None, related_name="accounts", to="buyer.internetaccount"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="banks",
            field=models.ManyToManyField(
                blank=True, related_name="buyers", to="buyer.bank"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="clads",
            field=models.ManyToManyField(through="buyer.BuyerClads", to="buyer.clad"),
        ),
        migrations.AddField(
            model_name="buyer",
            name="cryptos",
            field=models.ManyToManyField(
                blank=True, related_name="buyers", to="buyer.crypto"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="mobile_numbers",
            field=models.ManyToManyField(
                related_name="buyer_mobile_numbers",
                through="buyer.BuyerMobileNumber",
                to="buyer.mobilenumber",
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="mobiles",
            field=models.ManyToManyField(
                default=None, through="buyer.BuyerMobile", to="buyer.mobile"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="online_pays",
            field=models.ManyToManyField(
                blank=True, related_name="buyers", to="buyer.onlinepay"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="stuffs",
            field=models.ManyToManyField(through="buyer.BuyerStuff", to="buyer.stuff"),
        ),
    ]
