# Generated by Django 4.1.2 on 2022-12-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Наименование интернет-магазина",
                    ),
                ),
                (
                    "shop_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Мессенджер", "Мессенджер"),
                            ("Web-сайт", "Web-сайт"),
                            ("DarkNet", "DarkNet"),
                        ],
                        max_length=500,
                        null=True,
                        verbose_name="Тип магазина",
                    ),
                ),
                (
                    "shop_address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "shop_messanger_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Наименование мессенджера",
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Банковская карта", "Банковская карта"),
                            ("Электронные платежи", "Электронные платежи"),
                            ("Криптовалюта", "Криптовалюта"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название банка",
                    ),
                ),
                (
                    "bank_card_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер банковской карты",
                    ),
                ),
                (
                    "online_pay_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название платежной системы",
                    ),
                ),
                (
                    "online_pay_account",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер счета",
                    ),
                ),
                (
                    "crypto_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название криптовалюты",
                    ),
                ),
                (
                    "crypto_address_wallet",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Адрес кошелька",
                    ),
                ),
                (
                    "crime_place",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Кандалакшский района", "Кандалакшский района"),
                            ("Ковдорский район", "Ковдорский район"),
                            ("Кольский район", "Кольский район"),
                            ("Ловозерский район", "Ловозерский район"),
                            ("Печенгский район", "Печенгский район"),
                            ("Терский район", "Терский район"),
                            ("город Мурманск", "город Мурманск"),
                            (
                                "город Апатиты с подведомственной территорией",
                                "город Апатиты с подведомственной территорией",
                            ),
                            (
                                "ород Кировск с подведомственной территорией",
                                "город Кировск с подведомственной территорией",
                            ),
                            (
                                "город Оленегорск с подведомственной территорией",
                                "город Оленегорск с подведомственной территорией",
                            ),
                            (
                                "город Полярные Зори с подведомственной территорией",
                                "город Полярные Зори с подведомственной территорией",
                            ),
                            ("ЗАТО посёлок Видяево", "ЗАТО посёлок Видяево"),
                            ("ЗАТО город Заозёрск", "ЗАТО город Заозёрск"),
                            ("ЗАТО город Островной", "ЗАТО город Островной"),
                            ("ЗАТО город Североморск", "ЗАТО город Североморск"),
                            ("ЗАТО Александровск", "ЗАТО Александровск"),
                            (
                                "город Мончегорск с подведомственной территорией",
                                "город Мончегорск с подведомственной территорией",
                            ),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Место совершения преступления",
                    ),
                ),
                (
                    "arrest_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата задержания"
                    ),
                ),
                (
                    "clad_coordinates",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Координаты клада",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скупщик",
                "verbose_name_plural": "Скупщики",
            },
        ),
        migrations.CreateModel(
            name="CrimePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StuffType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Тип вещества",
                "verbose_name_plural": "Тип вещества",
            },
        ),
        migrations.CreateModel(
            name="BuyerAccount",
            fields=[
                (
                    "buyer",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="account",
                        serialize=False,
                        to="buyer.buyer",
                    ),
                ),
                (
                    "login",
                    models.CharField(max_length=100, null=True, verbose_name="Логин"),
                ),
                (
                    "password",
                    models.CharField(max_length=100, null=True, verbose_name="Пароль"),
                ),
                (
                    "app_password",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Пароль приложения"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Имя аккаунта"
                    ),
                ),
                (
                    "account_address",
                    models.CharField(
                        max_length=100, null=True, verbose_name="«Аккаунт-адрес»"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Абонентский номер (привязанный к аккаунту)",
                    ),
                ),
                (
                    "operator_nickname",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ник-нейм оператора",
                    ),
                ),
                (
                    "operator_account",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Аккаунт оператора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аккаунт пакупателя",
                "verbose_name_plural": "Аккаунт пакупателя",
            },
        ),
        migrations.CreateModel(
            name="Stuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mass",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Масса",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("мг", "мг"), ("г", "г"), ("кг", "кг")],
                        default="мг",
                        max_length=255,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="stuffs",
                        to="buyer.buyer",
                    ),
                ),
                (
                    "stuff_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="buyer.stufftype",
                        verbose_name="Вещество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вещество",
                "verbose_name_plural": "Вещества",
            },
        ),
        migrations.CreateModel(
            name="PhotoClad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("describe", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="")),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="buyer.buyer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobileNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(default=7, verbose_name="Код страны")),
                (
                    "number",
                    models.CharField(max_length=15, verbose_name="Номер телефона"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="numbers",
                        to="buyer.buyer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Номер телефона",
                "verbose_name_plural": "Телефонные номера",
            },
        ),
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imei",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="IMEI-номер"
                    ),
                ),
                (
                    "mobile_brand",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Марка"
                    ),
                ),
                (
                    "mobile_model",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Модель"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Пароль"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mobiles",
                        to="buyer.buyer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телефон",
                "verbose_name_plural": "Телефоны",
            },
        ),
    ]
