# Generated by Django 4.1.2 on 2022-10-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Photo",
            new_name="PhotoClad",
        ),
        migrations.RenameField(
            model_name="buyer",
            old_name="coordinates",
            new_name="account",
        ),
        migrations.AddField(
            model_name="buyer",
            name="clad_coordinates",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
