# Generated by Django 4.1.2 on 2023-04-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilenumber",
            name="number",
            field=models.CharField(max_length=17, verbose_name="Номер телефона"),
        ),
    ]
