# Generated by Django 4.1.2 on 2022-12-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0002_remove_stufftype_name_alter_stufftype_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stufftype",
            old_name="id",
            new_name="name",
        ),
    ]
