# Generated by Django 4.1.2 on 2022-10-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0002_rename_photo_photoclad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="imei",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
