# Generated by Django 4.1.2 on 2022-10-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0003_buyer_imei"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="account",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Аккаунт покупателя"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="arrest_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата задержания"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="clad_coordinates",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Координаты клада"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="crime_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="buyer.crimeplace",
                verbose_name="Место совершения преступления",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="imei",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="IMEI-номер"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="mobile_brand",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Марка"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="mobile_model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Модель"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="mobile_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="operator_account",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Аккаунт оператора"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="operator_nickname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ник-нейм оператора"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Пароль"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="payment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="buyer.payment",
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="shop_info",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Тип магазина"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="shop_name",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Наименование интернет-магазина",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="stuff_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="Масса вещества",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="stuff_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="buyer.stuff",
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="unit",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Единица измерения"
            ),
        ),
    ]
