# Generated by Django 4.1.2 on 2022-10-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0005_mobile_remove_buyer_imei_remove_buyer_mobile_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobile",
            name="imei",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
