# Generated by Django 4.1.2 on 2022-10-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0006_alter_mobile_imei"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobile",
            name="imei",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="IMEI-номер"
            ),
        ),
    ]
