# Generated by Django 4.1.2 on 2022-10-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0007_alter_mobile_imei"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="stuff_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="buyer.stuff",
                verbose_name="Тип вещества",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("мг", "мг"), ("г", "г"), ("кг", "кг")],
                max_length=255,
                null=True,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="stuff",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
