# Generated by Django 4.1.2 on 2022-10-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0008_alter_buyer_stuff_type_alter_buyer_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobilenumber",
            name="mobile",
        ),
        migrations.AddField(
            model_name="mobilenumber",
            name="buyer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="numbers",
                to="buyer.buyer",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="unit",
            field=models.CharField(
                choices=[("мг", "мг"), ("г", "г"), ("кг", "кг")],
                default="мг",
                max_length=255,
                verbose_name="Единица измерения",
            ),
        ),
    ]
