# Generated by Django 4.1.2 on 2022-10-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0010_remove_mobile_mobile_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="stuff_mass",
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="unit",
        ),
        migrations.AddField(
            model_name="stuff",
            name="stuff_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="Масса",
            ),
        ),
        migrations.AddField(
            model_name="stuff",
            name="unit",
            field=models.CharField(
                choices=[("мг", "мг"), ("г", "г"), ("кг", "кг")],
                default="мг",
                max_length=255,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="stuff_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="buyer.stuff",
                verbose_name="Вещество",
            ),
        ),
        migrations.AlterField(
            model_name="mobilenumber",
            name="code",
            field=models.IntegerField(default=7, verbose_name="Код страны"),
        ),
        migrations.AlterField(
            model_name="mobilenumber",
            name="number",
            field=models.CharField(max_length=15, verbose_name="Номер телефона"),
        ),
    ]
