# Generated by Django 4.1.2 on 2022-10-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0011_remove_buyer_stuff_mass_remove_buyer_unit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stuff",
            old_name="stuff_mass",
            new_name="mass",
        ),
    ]
