# Generated by Django 4.1.2 on 2022-10-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0012_rename_stuff_mass_stuff_mass"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="stuff_type",
        ),
        migrations.AddField(
            model_name="stuff",
            name="buyer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="stuffs",
                to="buyer.buyer",
            ),
        ),
    ]
