# Generated by Django 4.1.2 on 2022-10-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0013_remove_buyer_stuff_type_stuff_buyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="StuffType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="stuff",
            name="name",
        ),
        migrations.AddField(
            model_name="stuff",
            name="stuff_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="buyer.stufftype",
            ),
            preserve_default=False,
        ),
    ]
