# Generated by Django 4.1.2 on 2022-10-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0015_remove_buyer_shop_info_buyer_shop_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="account",
        ),
        migrations.AddField(
            model_name="buyer",
            name="account_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Аккаунт-адрес"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="account_login",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Логин"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="account_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя аккаунта"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Абонентский номер"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="account_password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Пароль"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="account_password_app",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Пароль приложения"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="shop_address",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="shop_messanger_name",
            field=models.CharField(
                default="", max_length=500, verbose_name="Наименование мессенджера"
            ),
            preserve_default=False,
        ),
    ]
