# Generated by Django 4.1.2 on 2022-10-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0016_remove_buyer_account_buyer_account_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="payment_type",
        ),
        migrations.AddField(
            model_name="buyer",
            name="payment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Банковская карта", "Банковская карта"),
                    ("Электронные платежи", "Электронные платежи"),
                    ("Криптовалюта", "Криптовалюта"),
                ],
                max_length=255,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
