# Generated by Django 4.1.2 on 2022-10-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0018_alter_buyer_crime_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="shop_messanger_name",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Наименование мессенджера",
            ),
        ),
    ]
